### ISSUE TITLE
[BUG] Cannot instantiate interface

### ISSUE THREAD

**Issue by Ame394** [opengento/magento2-gdpr#43]
## Description  
There's an issue during setup:upgrade with the module. It prevents us to upgrade to 2.3.4 because we can't complete our deployment process.

## Prerequisites  

**PHP Version:**
 - 7.3.16

**Magento Version:**
 - 2.3.4

**Module Version:**
 - dev-master

## Issue Details  

**Steps to reproduce the behavior**
php bin/magento setup:upgrade

**Expected behavior**  
Upgrade successful.

**Screenshots**  
```
PHP Fatal error:  Uncaught Error: Cannot instantiate interface Opengento\Gdpr\Api\ActionInterface in /var/www/html/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:50
Stack trace:
#0 /var/www/html/vendor/magento/framework/ObjectManager/ObjectManager.php(70): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Opengento\\Gdpr\\...')
#1 /var/www/html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(167): Magento\Framework\ObjectManager\ObjectManager->get('Opengento\\Gdpr\\...')
#2 /var/www/html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(273): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, 'Opengento\\Gdpr\\...', NULL, 'action', 'Opengento\\Gdpr\\...')
#3 /var/www/html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(236): Magento\Framework\ObjectManager\Factory\AbstractFactory->getResolvedArgument('Opengento\\Gdpr\\...', Array, Array)
#4 /var/www/html/vendor/magento/framework/ObjectManager/Factory/Dynam in /var/www/html/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php on line 50
```

**Comment by thomas-kl1** [comment]
Hi, I'm not able to reproduce the issue, have you some inputs on which argument the resolution is failing?

**Comment by thomas-kl1** [comment]
@Ame394 what was the issue?

**Comment by Ame394** [comment]
Sorry for that, I think I had a cache issue. Now it works well.
